#!/bin/bash

# Fedora Mail Server Setup Script
# This script automates the installation and configuration of Postfix and Dovecot
# Run as root or with sudo privileges

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_message() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if script is run as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root"
        exit 1
    fi
}

# Function to backup configuration files
backup_file() {
    local file=$1
    if [[ -f $file ]]; then
        cp "$file" "$file.backup.$(date +%Y%m%d_%H%M%S)"
        print_message "Backed up $file"
    fi
}

# Function to prompt for user input
prompt_input() {
    local prompt=$1
    local default=$2
    local input
    
    if [[ -n $default ]]; then
        read -p "$prompt [$default]: " input
        echo "${input:-$default}"
    else
        read -p "$prompt: " input
        echo "$input"
    fi
}

# Main installation function
install_mail_server() {
    print_message "Starting Fedora Mail Server Installation"
    print_message "========================================"

    # Check if running as root
    check_root

    # Get domain and hostname information
    print_message "Collecting configuration information..."
    CURRENT_HOSTNAME=$(hostname)
    CURRENT_DOMAIN=$(hostname -d 2>/dev/null || echo "example.com")
    
    DOMAIN=$(prompt_input "Enter your domain name" "$CURRENT_DOMAIN")
    HOSTNAME=$(prompt_input "Enter mail server hostname" "mail.$DOMAIN")
    ADMIN_EMAIL=$(prompt_input "Enter admin email address" "admin@$DOMAIN")
    
    print_message "Configuration Summary:"
    echo "  Domain: $DOMAIN"
    echo "  Mail Server: $HOSTNAME"
    echo "  Admin Email: $ADMIN_EMAIL"
    
    # Confirm installation
    read -p "Continue with installation? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_warning "Installation cancelled by user"
        exit 0
    fi

    # Update system
    print_message "Updating system packages..."
    dnf update -y || {
        print_error "Failed to update system"
        exit 1
    }

    # Install required packages
    print_message "Installing required packages..."
    dnf install -y postfix dovecot mailx cyrus-sasl cyrus-sasl-plain openssl firewalld || {
        print_error "Failed to install packages"
        exit 1
    }

    # Configure hostname
    print_message "Setting hostname..."
    hostnamectl set-hostname "$HOSTNAME"
    echo "$HOSTNAME" > /etc/hostname

    # Update /etc/hosts
    print_message "Updating /etc/hosts..."
    backup_file "/etc/hosts"
    IP_ADDRESS=$(hostname -I | awk '{print $1}')
    if ! grep -q "$HOSTNAME" /etc/hosts; then
        echo "$IP_ADDRESS $HOSTNAME $DOMAIN" >> /etc/hosts
    fi

    # Generate SSL certificates
    print_message "Generating SSL certificates..."
    SSL_DIR="/etc/ssl/mail"
    mkdir -p "$SSL_DIR"
    
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "$SSL_DIR/mail.key" \
        -out "$SSL_DIR/mail.crt" \
        -subj "/C=US/ST=State/L=City/O=Organization/CN=$HOSTNAME" \
        2>/dev/null

    chmod 600 "$SSL_DIR/mail.key"
    chmod 644 "$SSL_DIR/mail.crt"
    print_message "SSL certificates generated"

    # Configure Postfix
    print_message "Configuring Postfix..."
    backup_file "/etc/postfix/main.cf"
    
    # Backup default config and create new one
    cat > /etc/postfix/main.cf << EOF
# Postfix configuration generated by mail server setup script
# https://www.example.com

# Basic settings
myhostname = $HOSTNAME
mydomain = $DOMAIN
myorigin = \$mydomain
inet_interfaces = all
inet_protocols = ipv4
mydestination = \$myhostname, localhost.\$mydomain, localhost, \$mydomain
mynetworks = 127.0.0.0/8
home_mailbox = Maildir/
mailbox_command = 

# SMTP authentication
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_sasl_security_options = noanonymous
smtpd_sasl_local_domain = \$myhostname
broken_sasl_auth_clients = yes

# TLS parameters
smtpd_tls_cert_file = $SSL_DIR/mail.crt
smtpd_tls_key_file = $SSL_DIR/mail.key
smtpd_tls_security_level = may
smtp_tls_security_level = may
smtpd_tls_loglevel = 1
smtpd_tls_session_cache_database = btree:\${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:\${data_directory}/smtp_scache

# Restrictions
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination

# Message size limit (25MB)
message_size_limit = 26214400

# Mailbox size limit (1GB)
mailbox_size_limit = 1073741824
EOF

    # Configure Postfix master.cf for submission port
    backup_file "/etc/postfix/master.cf"
    if ! grep -q "^submission" /etc/postfix/master.cf; then
        cat >> /etc/postfix/master.cf << EOF
submission inet n       -       n       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
EOF
    fi

    # Configure Dovecot
    print_message "Configuring Dovecot..."
    backup_file "/etc/dovecot/dovecot.conf"
    
    # Main Dovecot config
    cat > /etc/dovecot/dovecot.conf << EOF
# Dovecot configuration generated by mail server setup script

protocols = imap pop3 lmtp
listen = *

# SSL configuration
ssl = required
ssl_cert = <$SSL_DIR/mail.crt
ssl_key = <$SSL_DIR/mail.key
ssl_min_protocol = TLSv1.2
ssl_cipher_list = HIGH:!aNULL:!MD5

# Authentication
auth_mechanisms = plain login
!include auth-system.conf.ext

# Mail location
mail_location = maildir:~/Maildir
namespace inbox {
  inbox = yes
}

# Service configurations
service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

# Logging
log_path = /var/log/dovecot.log
info_log_path = /var/log/dovecot-info.log
debug_log_path = /var/log/dovecot-debug.log
EOF

    # Configure Dovecot 10-mail.conf
    cat > /etc/dovecot/conf.d/10-mail.conf << EOF
mail_location = maildir:~/Maildir
namespace inbox {
  inbox = yes
}
mail_privileged_group = mail
EOF

    # Configure Dovecot 10-auth.conf
    sed -i 's/#disable_plaintext_auth = yes/disable_plaintext_auth = no/' /etc/dovecot/conf.d/10-auth.conf
    sed -i 's/auth_mechanisms = plain/auth_mechanisms = plain login/' /etc/dovecot/conf.d/10-auth.conf

    # Configure Dovecot 10-master.conf
    cat > /etc/dovecot/conf.d/10-master.conf << EOF
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 110
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service lmtp {
  unix_listener lmtp {
    mode = 0666
  }
}

service auth {
  unix_listener auth-userdb {
    mode = 0666
    user = dovecot
    group = dovecot
  }
  
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  
  user = dovecot
}

service auth-worker {
  user = dovecot
}
EOF

    # Create Maildir for users
    print_message "Creating Maildir for existing users..."
    for user in $(getent passwd | grep -E ":/home/[^:]+" | cut -d: -f1); do
        if [[ -d "/home/$user" ]]; then
            maildir="/home/$user/Maildir"
            mkdir -p "$maildir"/{cur,new,tmp}
            chown -R "$user:$user" "$maildir"
            chmod -R 700 "$maildir"
            print_message "Created Maildir for user: $user"
        fi
    done

    # Configure firewall
    print_message "Configuring firewall..."
    systemctl start firewalld
    systemctl enable firewalld
    
    firewall-cmd --permanent --add-service=smtp
    firewall-cmd --permanent --add-service=smtps
    firewall-cmd --permanent --add-service=imap
    firewall-cmd --permanent --add-service=imaps
    firewall-cmd --permanent --add-service=pop3
    firewall-cmd --permanent --add-service=pop3s
    firewall-cmd --permanent --add-port=587/tcp  # submission
    firewall-cmd --reload
    
    print_message "Firewall configured"

    # Start and enable services
    print_message "Starting services..."
    systemctl restart postfix
    systemctl enable postfix
    
    systemctl restart dovecot
    systemctl enable dovecot

    # Check service status
    print_message "Checking service status..."
    if systemctl is-active --quiet postfix; then
        print_message "Postfix is running"
    else
        print_error "Postfix failed to start"
    fi
    
    if systemctl is-active --quiet dovecot; then
        print_message "Dovecot is running"
    else
        print_error "Dovecot failed to start"
    fi

    # Create test script
    print_message "Creating test script..."
    cat > /usr/local/bin/test-mailserver.sh << 'EOF'
#!/bin/bash
# Test script for mail server

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

echo "Testing mail server configuration..."
echo "==================================="

# Test Postfix
echo -n "Postfix status: "
if systemctl is-active --quiet postfix; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test Dovecot
echo -n "Dovecot status: "
if systemctl is-active --quiet dovecot; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test SMTP connection
echo -n "SMTP port (25): "
if nc -zv localhost 25 2>&1 | grep -q succeeded; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test submission port
echo -n "Submission port (587): "
if nc -zv localhost 587 2>&1 | grep -q succeeded; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test IMAP
echo -n "IMAP port (143): "
if nc -zv localhost 143 2>&1 | grep -q succeeded; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test IMAPS
echo -n "IMAPS port (993): "
if nc -zv localhost 993 2>&1 | grep -q succeeded; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

# Test POP3
echo -n "POP3 port (110): "
if nc -zv localhost 110 2>&1 | grep -q succeeded; then
    echo -e "${GREEN}OK${NC}"
else
    echo -e "${RED}FAILED${NC}"
fi

echo "==================================="
echo "Check logs with: tail -f /var/log/maillog"
EOF

    chmod +x /usr/local/bin/test-mailserver.sh

    # Create email user management script
    print_message "Creating email user management script..."
    cat > /usr/local/bin/manage-email-users.sh << 'EOF'
#!/bin/bash
# Email user management script

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

show_menu() {
    clear
    echo "Email User Management"
    echo "===================="
    echo "1) List email users"
    echo "2) Add email user"
    echo "3) Delete email user"
    echo "4) Change password"
    echo "5) Show mailbox size"
    echo "6) Exit"
    echo -n "Choose an option: "
}

list_users() {
    echo -e "${GREEN}Email Users:${NC}"
    echo "============"
    for user in $(getent passwd | grep -E ":/home/[^:]+" | cut -d: -f1); do
        if [[ -d "/home/$user/Maildir" ]]; then
            echo "  $user@$(hostname -d 2>/dev/null || hostname)"
        fi
    done
    echo
    read -p "Press Enter to continue..."
}

add_user() {
    echo -e "${GREEN}Add Email User${NC}"
    echo "=============="
    read -p "Username: " username
    
    if id "$username" &>/dev/null; then
        echo -e "${YELLOW}User already exists${NC}"
        
        # Ensure Maildir exists
        maildir="/home/$username/Maildir"
        if [[ ! -d "$maildir" ]]; then
            mkdir -p "$maildir"/{cur,new,tmp}
            chown -R "$username:$username" "$maildir"
            chmod -R 700 "$maildir"
            echo "Maildir created for existing user"
        fi
    else
        # Create new user
        useradd -m -s /sbin/nologin "$username"
        
        # Set password
        passwd "$username"
        
        # Create Maildir
        maildir="/home/$username/Maildir"
        mkdir -p "$maildir"/{cur,new,tmp}
        chown -R "$username:$username" "$maildir"
        chmod -R 700 "$maildir"
        
        echo -e "${GREEN}User $username created successfully${NC}"
    fi
    
    echo
    read -p "Press Enter to continue..."
}

delete_user() {
    echo -e "${RED}Delete Email User${NC}"
    echo "================"
    read -p "Username to delete: " username
    
    if id "$username" &>/dev/null; then
        read -p "Delete home directory? (y/n): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            userdel -r "$username"
        else
            userdel "$username"
        fi
        echo -e "${GREEN}User $username deleted${NC}"
    else
        echo -e "${RED}User not found${NC}"
    fi
    
    echo
    read -p "Press Enter to continue..."
}

change_password() {
    echo -e "${GREEN}Change Password${NC}"
    echo "==============="
    read -p "Username: " username
    
    if id "$username" &>/dev/null; then
        passwd "$username"
    else
        echo -e "${RED}User not found${NC}"
    fi
    
    echo
    read -p "Press Enter to continue..."
}

show_mailbox_size() {
    echo -e "${GREEN}Mailbox Sizes${NC}"
    echo "============="
    
    total_size=0
    for user in $(getent passwd | grep -E ":/home/[^:]+" | cut -d: -f1); do
        if [[ -d "/home/$user/Maildir" ]]; then
            size=$(du -sh "/home/$user/Maildir" 2>/dev/null | cut -f1)
            echo "  $user@$(hostname -d): $size"
            total_size=$((total_size + $(du -s "/home/$user/Maildir" 2>/dev/null | cut -f1)))
        fi
    done
    
    echo "  -------------------"
    echo "  Total: $total_size KB"
    echo
    read -p "Press Enter to continue..."
}

# Main loop
while true; do
    show_menu
    read choice
    
    case $choice in
        1) list_users ;;
        2) add_user ;;
        3) delete_user ;;
        4) change_password ;;
        5) show_mailbox_size ;;
        6) exit 0 ;;
        *) echo -e "${RED}Invalid option${NC}"; sleep 1 ;;
    esac
done
EOF

    chmod +x /usr/local/bin/manage-email-users.sh

    # Add SSL renewal cron job
    print_message "Setting up SSL certificate renewal cron job..."
    cat > /etc/cron.weekly/renew-ssl.sh << EOF
#!/bin/bash
# Renew self-signed SSL certificate for mail server

SSL_DIR="/etc/ssl/mail"
HOSTNAME="$(hostname)"

# Generate new certificate (valid for 365 days)
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout "\$SSL_DIR/mail.key.new" \
    -out "\$SSL_DIR/mail.crt.new" \
    -subj "/C=US/ST=State/L=City/O=Organization/CN=\$HOSTNAME" \
    2>/dev/null

if [[ \$? -eq 0 ]]; then
    mv "\$SSL_DIR/mail.key.new" "\$SSL_DIR/mail.key"
    mv "\$SSL_DIR/mail.crt.new" "\$SSL_DIR/mail.crt"
    chmod 600 "\$SSL_DIR/mail.key"
    chmod 644 "\$SSL_DIR/mail.crt"
    
    # Restart services
    systemctl restart postfix
    systemctl restart dovecot
    
    logger "Mail server SSL certificate renewed"
fi
EOF

    chmod +x /etc/cron.weekly/renew-ssl.sh

    # Create README file
    print_message "Creating README file..."
    cat > ~/mail-server-info.txt << EOF
Fedora Mail Server Installation Summary
=======================================
Installation Date: $(date)
Domain: $DOMAIN
Mail Server: $HOSTNAME
Admin Email: $ADMIN_EMAIL

Configuration Files:
  - Postfix: /etc/postfix/main.cf
  - Dovecot: /etc/dovecot/dovecot.conf
  - SSL Certificates: /etc/ssl/mail/

Useful Commands:
  - Check service status: systemctl status postfix dovecot
  - View mail logs: tail -f /var/log/maillog
  - Test server: /usr/local/bin/test-mailserver.sh
  - Manage users: /usr/local/bin/manage-email-users.sh
  - Send test email: echo "Test" | mail -s "Test" user@domain.com

Firewall Ports Opened:
  - SMTP: 25
  - SMTP Submission: 587
  - SMTPS: 465
  - IMAP: 143
  - IMAPS: 993
  - POP3: 110
  - POP3S: 995

Email Client Configuration:
  Incoming Server: $HOSTNAME
    - IMAP: Port 143 (STARTTLS) or 993 (SSL/TLS)
    - POP3: Port 110 (STARTTLS) or 995 (SSL/TLS)
  Outgoing Server (SMTP): $HOSTNAME
    - Port 587 (STARTTLS) or 465 (SSL/TLS)
  Authentication: Normal password
  Username: Your system username

Next Steps:
  1. Set up SPF, DKIM, and DMARC records for better deliverability
  2. Consider installing a webmail client like Roundcube
  3. Set up monitoring and backups
  4. Configure spam filtering (SpamAssassin)
EOF

    print_message "Installation Complete!"
    print_message "======================="
    echo ""
    echo "Summary has been saved to: ~/mail-server-info.txt"
    echo ""
    echo "Next steps:"
    echo "  1. Review the configuration files"
    echo "  2. Test your server with: /usr/local/bin/test-mailserver.sh"
    echo "  3. Add email users with: /usr/local/bin/manage-email-users.sh"
    echo "  4. Configure your email client using the settings above"
    echo "  5. Check /var/log/maillog for any errors"
    echo ""
    echo "For better email deliverability, consider setting up:"
    echo "  - SPF records in your DNS"
    echo "  - DKIM signing"
    echo "  - DMARC policy"
    echo "  - Reverse DNS (PTR record)"
}

# Run the installation
install_mail_server

# Display final message
print_message "Installation script finished"
print_warning "Please review the configuration and test thoroughly before using in production"